export const NASDAQ_50_DATA = [
  { symbol: "AAPL", name: "Apple Inc.", sector: "Technology" },
  { symbol: "MSFT", name: "Microsoft Corp", sector: "Technology" },
  { symbol: "NVDA", name: "NVIDIA Corp", sector: "Technology" },
  { symbol: "GOOGL", name: "Alphabet Inc.", sector: "Technology" },
  { symbol: "AMZN", name: "Amazon.com Inc", sector: "Consumer Cyclical" },
  { symbol: "META", name: "Meta Platforms", sector: "Technology" },
  { symbol: "TSLA", name: "Tesla Inc", sector: "Consumer Cyclical" },
  { symbol: "AVGO", name: "Broadcom Inc", sector: "Technology" },
  { symbol: "ASML", name: "ASML Holding", sector: "Technology" },
  { symbol: "COST", name: "Costco Wholesale", sector: "Consumer Defensive" },
  { symbol: "PEP", name: "PepsiCo Inc", sector: "Consumer Defensive" },
  { symbol: "NFLX", name: "Netflix Inc", sector: "Communication" },
  { symbol: "AMD", name: "Advanced Micro Devices", sector: "Technology" },
  { symbol: "ADBE", name: "Adobe Inc", sector: "Technology" },
  { symbol: "AZN", name: "AstraZeneca", sector: "Healthcare" },
  { symbol: "CSCO", name: "Cisco Systems", sector: "Technology" },
  { symbol: "TMUS", name: "T-Mobile US", sector: "Communication" },
  { symbol: "INTC", name: "Intel Corp", sector: "Technology" },
  { symbol: "TXN", name: "Texas Instruments", sector: "Technology" },
  { symbol: "CMCSA", name: "Comcast Corp", sector: "Communication" },
  { symbol: "AMGN", name: "Amgen Inc", sector: "Healthcare" },
  { symbol: "HON", name: "Honeywell Intl", sector: "Industrials" },
  { symbol: "INTU", name: "Intuit Inc", sector: "Technology" },
  { symbol: "QCOM", name: "Qualcomm Inc", sector: "Technology" },
  { symbol: "ISRG", name: "Intuitive Surgical", sector: "Healthcare" },
  { symbol: "BKNG", name: "Booking Holdings", sector: "Consumer Cyclical" },
  { symbol: "VRTX", name: "Vertex Pharma", sector: "Healthcare" },
  { symbol: "GILD", name: "Gilead Sciences", sector: "Healthcare" },
  { symbol: "SBUX", name: "Starbucks Corp", sector: "Consumer Cyclical" },
  { symbol: "MDLZ", name: "Mondelez Intl", sector: "Consumer Defensive" },
  { symbol: "ADP", name: "Auto Data Process", sector: "Industrials" },
  { symbol: "ADI", name: "Analog Devices", sector: "Technology" },
  { symbol: "REGN", name: "Regeneron Pharma", sector: "Healthcare" },
  { symbol: "LRCX", name: "Lam Research", sector: "Technology" },
  { symbol: "PANW", name: "Palo Alto Networks", sector: "Technology" },
  { symbol: "MU", name: "Micron Tech", sector: "Technology" },
  { symbol: "SNPS", name: "Synopsys Inc", sector: "Technology" },
  { symbol: "KLAC", name: "KLA Corp", sector: "Technology" },
  { symbol: "CDNS", name: "Cadence Design", sector: "Technology" },
  { symbol: "MELI", name: "MercadoLibre", sector: "Consumer Cyclical" },
  { symbol: "MAR", name: "Marriott Intl", sector: "Consumer Cyclical" },
  { symbol: "CSX", name: "CSX Corp", sector: "Industrials" },
  { symbol: "ORLY", name: "O'Reilly Auto", sector: "Consumer Cyclical" },
  { symbol: "MNST", name: "Monster Beverage", sector: "Consumer Defensive" },
  { symbol: "PYPL", name: "PayPal Holdings", sector: "Financial" },
  { symbol: "ABNB", name: "Airbnb Inc", sector: "Consumer Cyclical" },
  { symbol: "LULU", name: "Lululemon Athletica", sector: "Consumer Cyclical" },
  { symbol: "WDAY", name: "Workday Inc", sector: "Technology" },
  { symbol: "CTAS", name: "Cintas Corp", sector: "Industrials" },
  { symbol: "CRWD", name: "CrowdStrike", sector: "Technology" }
];
